/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fenetre.Dette;


import Entity.Client;
import Entity.Dette;
import Metier.ClientMetier;
import Metier.Fichier;
import java.awt.Color;
import java.time.Instant;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import ridayasoft.Metier;

/**
 *
 * @author Gauss
 */
public class PretDetteForm extends javax.swing.JPanel {

    /**
     * Creates new form GestionUserForm
     */
    EntityManagerFactory emf;
    EntityManager em;
    Metier metier = new Metier();
    int nombreEmprunt = 0;
    Client idClient;
    ClientMetier clientMetier = new ClientMetier();

    public PretDetteForm() {
        initComponents();
        try {
            emf = Persistence.createEntityManagerFactory("RidayaSoftPU");
            em = emf.createEntityManager();
//            lblQtDispoTypeBidon.setVisible(false);
            cbClient();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    public void cbClient() {
        Query qrClient = em.createNamedQuery("Client.findAll");
        List<Client> listClient = qrClient.getResultList();
        cbClientNom.removeAllItems();

        for (Client client : listClient) {
            cbClientNom.addItem(client.getNomClient());
        }
        cbClientNom.setSelectedIndex(-1);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btPretDetteSave = new javax.swing.JButton();
        btPretDetteReset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbClientNom = new javax.swing.JComboBox();
        txtMontantDettePret = new javax.swing.JTextField();
        cbDevisePret = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dette : Prêt");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Dette :Prêt");

        btPretDetteSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btPretDetteSave.setForeground(new java.awt.Color(0, 207, 255));
        btPretDetteSave.setText("Valider");
        btPretDetteSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 207, 255)));
        btPretDetteSave.setContentAreaFilled(false);
        btPretDetteSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btPretDetteSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btPretDetteSaveMouseExited(evt);
            }
        });
        btPretDetteSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPretDetteSaveActionPerformed(evt);
            }
        });

        btPretDetteReset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btPretDetteReset.setForeground(new java.awt.Color(0, 207, 255));
        btPretDetteReset.setText("Reinitialiser");
        btPretDetteReset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 207, 255)));
        btPretDetteReset.setContentAreaFilled(false);
        btPretDetteReset.setPreferredSize(new java.awt.Dimension(57, 35));
        btPretDetteReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btPretDetteResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btPretDetteResetMouseExited(evt);
            }
        });
        btPretDetteReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPretDetteResetActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setText("Nom Client : ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel3.setText("Montant : ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel8.setText("Devise :");

        cbClientNom.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cbClientNom.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbClientNomPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        txtMontantDettePret.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtMontantDettePret.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMontantDettePretKeyReleased(evt);
            }
        });

        cbDevisePret.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cbDevisePret.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CDF" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(84, 84, 84)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMontantDettePret)
                    .addComponent(cbClientNom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbDevisePret, 0, 180, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbClientNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMontantDettePret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbDevisePret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(btPretDetteSave, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btPretDetteReset, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addGap(269, 269, 269))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPretDetteSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPretDetteReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btPretDetteSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPretDetteSaveActionPerformed
        try {
             if (cbClientNom.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(null, "Verifier le nom du client !", "RidayaSoft : Dette", JOptionPane.ERROR_MESSAGE);
        } else if (txtMontantDettePret.getText().length() < 3) {
                JOptionPane.showMessageDialog(null, "Verifier le montant !", "RidayaSoft : Dette", JOptionPane.ERROR_MESSAGE);
        } else {

                EntityTransaction transaction = em.getTransaction();
                try {
                       
                    Dette dette = new Dette();
                    dette.setIdClient(idClient);
                    dette.setDateDette(Date.from(Instant.now()));
                    dette.setMontantDette(Double.parseDouble(txtMontantDettePret.getText()));
                    dette.setDevise(cbDevisePret.getSelectedItem().toString());
                    
                    
            transaction.begin();
            em.persist(dette);
            transaction.commit();
            JOptionPane.showMessageDialog(null, "Dette validéé !", "Ridaya Soft : Dette", JOptionPane.INFORMATION_MESSAGE);
            new Fichier().ecrireFichierLogAccess("Validation dette de " + cbClientNom.getSelectedItem() + " à " + Date.from(Instant.now()) + " Montant : " + txtMontantDettePret.getText() + " FC");
                    
                    init();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erreur, contacte l'Administrateur au 814444084 !\n \n" + e.getMessage());
                    init();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur, veuillez contacter l'administrateur !");
        }
    }//GEN-LAST:event_btPretDetteSaveActionPerformed
    public void init() {
        cbClientNom.setSelectedIndex(-1);
        txtMontantDettePret.setText("");
        
    }
    private void btPretDetteResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPretDetteResetActionPerformed
        init();
    }//GEN-LAST:event_btPretDetteResetActionPerformed

    private void btPretDetteSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPretDetteSaveMouseEntered
        btPretDetteSave.setForeground(Color.red);
    }//GEN-LAST:event_btPretDetteSaveMouseEntered

    private void btPretDetteSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPretDetteSaveMouseExited
        btPretDetteSave.setForeground(btPretDetteReset.getForeground());
    }//GEN-LAST:event_btPretDetteSaveMouseExited

    private void btPretDetteResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPretDetteResetMouseEntered
        btPretDetteReset.setForeground(Color.red);
    }//GEN-LAST:event_btPretDetteResetMouseEntered

    private void btPretDetteResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPretDetteResetMouseExited
        btPretDetteReset.setForeground(btPretDetteSave.getForeground());
    }//GEN-LAST:event_btPretDetteResetMouseExited
    
    private void cbClientNomPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbClientNomPopupMenuWillBecomeInvisible
       try {
            idClient = clientMetier.clientParNom(em, cbClientNom.getSelectedItem().toString());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cbClientNomPopupMenuWillBecomeInvisible

    private void txtMontantDettePretKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontantDettePretKeyReleased
         if (!metier.isNumeric(evt.getKeyChar())) {
            txtMontantDettePret.setText(txtMontantDettePret.getText().replace(String.valueOf(evt.getKeyChar()), ""));
        }
    }//GEN-LAST:event_txtMontantDettePretKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPretDetteReset;
    private javax.swing.JButton btPretDetteSave;
    private javax.swing.JComboBox cbClientNom;
    private javax.swing.JComboBox cbDevisePret;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField txtMontantDettePret;
    // End of variables declaration//GEN-END:variables
}
