/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fenetre.Dette;

import Entity.Client;
import Entity.Remboursement;
import Metier.ClientMetier;
import Metier.DetteMetier;
import Metier.Fichier;
import java.awt.Color;
import java.time.Instant;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import ridayasoft.Metier;

/**
 *
 * @author Gauss
 */
public class RemboursementDetteForm extends javax.swing.JPanel {

    /**
     * Creates new form GestionUserForm
     */
    EntityManagerFactory emf;
    EntityManager em;
    Metier metier = new Metier();
    Client idClient;
    ClientMetier clientMetier = new ClientMetier();
    
    public RemboursementDetteForm() {
        initComponents();
        try {
            emf = Persistence.createEntityManagerFactory("RidayaSoftPU");
            em = emf.createEntityManager();

            // Chargement de clients qui ont emprunté
            cbClient();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public void cbClient() {
        List listClient = new DetteMetier().clientInsovable(em);
        cbNomClient.removeAllItems();
        
        for (Object client : listClient) {
            Object[] clientTab = (Object[]) client;
            if (Double.parseDouble(clientTab[0].toString()) > 0) { // Condition : Juste avoir ceux qui doivent rembourser
                cbNomClient.addItem(clientTab[1]);
            }
        }
        cbNomClient.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btStockBidonSave = new javax.swing.JButton();
        btUserReset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMontantPayerDette = new javax.swing.JTextField();
        cbNomClient = new javax.swing.JComboBox();
        txtMontantTotalRemboursement = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dette : Remboursement");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Remboursement :Dette");

        btStockBidonSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btStockBidonSave.setForeground(new java.awt.Color(0, 207, 255));
        btStockBidonSave.setText("Valider");
        btStockBidonSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 207, 255)));
        btStockBidonSave.setContentAreaFilled(false);
        btStockBidonSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btStockBidonSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btStockBidonSaveMouseExited(evt);
            }
        });
        btStockBidonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStockBidonSaveActionPerformed(evt);
            }
        });

        btUserReset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btUserReset.setForeground(new java.awt.Color(0, 207, 255));
        btUserReset.setText("Reinitialiser");
        btUserReset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 207, 255)));
        btUserReset.setContentAreaFilled(false);
        btUserReset.setPreferredSize(new java.awt.Dimension(57, 35));
        btUserReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btUserResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btUserResetMouseExited(evt);
            }
        });
        btUserReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUserResetActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setText("Nom Client : ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel3.setText("Somme total à payer : ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel8.setText("Montant payer :");

        txtMontantPayerDette.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtMontantPayerDette.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMontantPayerDetteKeyReleased(evt);
            }
        });

        cbNomClient.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cbNomClient.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbNomClientPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        txtMontantTotalRemboursement.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbNomClient, javax.swing.GroupLayout.Alignment.LEADING, 0, 180, Short.MAX_VALUE)
                        .addComponent(txtMontantPayerDette))
                    .addComponent(txtMontantTotalRemboursement, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbNomClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMontantTotalRemboursement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMontantPayerDette, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btStockBidonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btUserReset, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(291, 291, 291))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btStockBidonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btUserReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btStockBidonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStockBidonSaveActionPerformed
        try {
            if (cbNomClient.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(null, "Verifier le nom du client !", "RidayaSoft : Remise bidon", JOptionPane.ERROR_MESSAGE);
                
            } else if (Double.parseDouble(txtMontantPayerDette.getText()) > Double.parseDouble(txtMontantTotalRemboursement.getText())) {
                JOptionPane.showMessageDialog(null, "Le montant payé ne doit pas être superieur au montant emprunter !", "RidayaSoft : Remboursement Dette", JOptionPane.ERROR_MESSAGE);
                
            } else if (txtMontantPayerDette.getText().length() < 3) {
                JOptionPane.showMessageDialog(null, "Verifier le montant !", "RidayaSoft : Remboursement Dette", JOptionPane.ERROR_MESSAGE);
        } else {
                
                EntityTransaction transaction = em.getTransaction();
                
                try {
                    
                    Remboursement remboursement = new Remboursement();
                    remboursement.setIdClient(idClient);
                    remboursement.setDateRemboursement(Date.from(Instant.now()));
                    remboursement.setDeviseRemboursement("CDF");
                    remboursement.setMontantRemboursement(Double.parseDouble(txtMontantPayerDette.getText()));
                    
                    transaction.begin();
                    em.persist(remboursement);
                    transaction.commit();
                    JOptionPane.showMessageDialog(null, "Paiement validé !", "Ridaya Soft : Dette Remboursement", JOptionPane.INFORMATION_MESSAGE);
                    new Fichier().ecrireFichierLogAccess("Validation du remboursement dette de " + cbNomClient.getSelectedItem() + " à " + Date.from(Instant.now()) + " Montant : " + txtMontantPayerDette.getText() + " FC");
                    
                    init();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erreur, contacte l'Administrateur au 814444084 !\n \n" + e.getMessage());
                    init();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur, contacte l'Administrateur au 814444084 !\n \n" + e.getMessage());
        }
    }//GEN-LAST:event_btStockBidonSaveActionPerformed
    public void init() {
        cbNomClient.setSelectedIndex(-1);
        txtMontantTotalRemboursement.setText("");
        txtMontantPayerDette.setText("");
        
    }
    private void btUserResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUserResetActionPerformed
        init();
    }//GEN-LAST:event_btUserResetActionPerformed

    private void btStockBidonSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btStockBidonSaveMouseEntered
        btStockBidonSave.setForeground(Color.red);
    }//GEN-LAST:event_btStockBidonSaveMouseEntered

    private void btStockBidonSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btStockBidonSaveMouseExited
        btStockBidonSave.setForeground(btUserReset.getForeground());
    }//GEN-LAST:event_btStockBidonSaveMouseExited

    private void btUserResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btUserResetMouseEntered
        btUserReset.setForeground(Color.red);
    }//GEN-LAST:event_btUserResetMouseEntered

    private void btUserResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btUserResetMouseExited
        btUserReset.setForeground(btStockBidonSave.getForeground());
    }//GEN-LAST:event_btUserResetMouseExited

    private void txtMontantPayerDetteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontantPayerDetteKeyReleased
        if (!metier.isNumeric(evt.getKeyChar())) {
            txtMontantPayerDette.setText(txtMontantPayerDette.getText().replace(String.valueOf(evt.getKeyChar()), ""));
        }
    }//GEN-LAST:event_txtMontantPayerDetteKeyReleased

    private void cbNomClientPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbNomClientPopupMenuWillBecomeInvisible
        try {
            idClient = clientMetier.clientParNom(em, cbNomClient.getSelectedItem().toString());
            
            DetteMetier detteMetier = new DetteMetier();
            List listInfoDetteClient = detteMetier.clientInsovableMontantparClient(em, idClient.getIdClient());
            
            for (Object client : listInfoDetteClient) {
                Object[] clientTab = (Object[]) client;
                txtMontantTotalRemboursement.setText(clientTab[0].toString());
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_cbNomClientPopupMenuWillBecomeInvisible


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btStockBidonSave;
    private javax.swing.JButton btUserReset;
    private javax.swing.JComboBox cbNomClient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField txtMontantPayerDette;
    private javax.swing.JTextField txtMontantTotalRemboursement;
    // End of variables declaration//GEN-END:variables
}
