/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fenetre.Gestion;

import Entity.Famille;
import Entity.Produit;
import Metier.Fichier;
import java.awt.Color;
import java.time.Instant;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import ridayasoft.Metier;

/**
 *
 * @author Gauss
 */
public class GestionProduitForm extends javax.swing.JPanel {

    EntityManagerFactory emf;
    EntityManager em;
    Famille idFamille;
    Metier metier = new Metier();

    public GestionProduitForm() {
        initComponents();
        try {
            emf = Persistence.createEntityManagerFactory("RidayaSoftPU");
            em = emf.createEntityManager();
            cbFamille();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btProduitSave = new javax.swing.JButton();
        txtProduitNom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtProduitPrixUnitaire = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtProduitSeuil = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cboFamille = new javax.swing.JComboBox();
        btProduitReset = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion : Produit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("Enregistrement : Produit");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel3.setText("Famille : ");

        btProduitSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btProduitSave.setForeground(new java.awt.Color(0, 207, 255));
        btProduitSave.setText("Valider");
        btProduitSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 207, 255)));
        btProduitSave.setContentAreaFilled(false);
        btProduitSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btProduitSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btProduitSaveMouseExited(evt);
            }
        });
        btProduitSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProduitSaveActionPerformed(evt);
            }
        });

        txtProduitNom.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtProduitNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProduitNomActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel4.setText("Nom du produit :");

        txtProduitPrixUnitaire.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtProduitPrixUnitaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProduitPrixUnitaireActionPerformed(evt);
            }
        });
        txtProduitPrixUnitaire.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProduitPrixUnitaireKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel6.setText("Prix de vente : ");

        txtProduitSeuil.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtProduitSeuil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProduitSeuilActionPerformed(evt);
            }
        });
        txtProduitSeuil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProduitSeuilKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel7.setText("Seuil :");

        cboFamille.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cboFamille.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboFamillePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        btProduitReset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btProduitReset.setForeground(new java.awt.Color(0, 207, 255));
        btProduitReset.setText("Reinitialiser");
        btProduitReset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 207, 255)));
        btProduitReset.setContentAreaFilled(false);
        btProduitReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btProduitResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btProduitResetMouseExited(evt);
            }
        });
        btProduitReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProduitResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProduitSeuil, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProduitPrixUnitaire, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cboFamille, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtProduitNom, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(btProduitSave, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btProduitReset, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboFamille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtProduitNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtProduitPrixUnitaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtProduitSeuil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btProduitSave, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btProduitReset, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btProduitSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProduitSaveActionPerformed
        try {
            
        
        if (cboFamille.getSelectedIndex() == -1 || txtProduitNom.getText().length() < 3 || txtProduitPrixUnitaire.getText().length() < 3) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir les champs vide !", "Ridaya Soft : Produit", JOptionPane.ERROR_MESSAGE);
        } else {
            Produit produit = new Produit();
            if (txtProduitSeuil.getText().isEmpty()) {
                produit.setSeuil(0);
            } else {
                produit.setSeuil(Integer.parseInt(txtProduitSeuil.getText()));
            }

            produit.setDateCreation(Date.from(Instant.now()));
            produit.setIdFamille(idFamille);
            produit.setNomProduit(txtProduitNom.getText());
            produit.setPrixUnitaire(Double.parseDouble(txtProduitPrixUnitaire.getText()));

            EntityTransaction transaction = em.getTransaction();
            transaction.begin();
            em.persist(produit);
            transaction.commit();
            new Fichier().ecrireFichierLogAccess("Ajout du produit " + txtProduitNom.getText() + " à " + Date.from(Instant.now()));
            JOptionPane.showMessageDialog(null, "Produit ajouter avec succes !", "Ridaya Soft : Produit", JOptionPane.INFORMATION_MESSAGE);
              
            init();
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btProduitSaveActionPerformed
    public void init() {
        cboFamille.setSelectedIndex(-1);
        txtProduitNom.setText("");
        txtProduitPrixUnitaire.setText("");
        txtProduitSeuil.setText("");
    }
    private void txtProduitNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProduitNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProduitNomActionPerformed

    private void txtProduitPrixUnitaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProduitPrixUnitaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProduitPrixUnitaireActionPerformed

    private void txtProduitSeuilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProduitSeuilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProduitSeuilActionPerformed

    private void cboFamillePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboFamillePopupMenuWillBecomeInvisible
        try {
            Query qrFamille = em.createNamedQuery("Famille.findByDesignation");
        qrFamille.setParameter("designation", cboFamille.getSelectedItem());
        List<Famille> listFamille = qrFamille.getResultList();
        Famille lastFamille = listFamille.get(listFamille.size() - 1); // Last Id
        idFamille = lastFamille;
        } catch (Exception e) {
        }
//        JOptionPane.showMessageDialog(null, "Pour " + lastFamille.getIdFamille() + " qui est " + lastFamille.getDesignation() );
    }//GEN-LAST:event_cboFamillePopupMenuWillBecomeInvisible

    private void btProduitResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProduitResetActionPerformed
        init();
    }//GEN-LAST:event_btProduitResetActionPerformed

    private void txtProduitPrixUnitaireKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProduitPrixUnitaireKeyReleased
        
        if (!metier.isNumeric(evt.getKeyChar())) {
            txtProduitPrixUnitaire.setText(txtProduitPrixUnitaire.getText().replace(String.valueOf(evt.getKeyChar()),""));
        }
    }//GEN-LAST:event_txtProduitPrixUnitaireKeyReleased

    private void txtProduitSeuilKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProduitSeuilKeyReleased
        if (!metier.isNumeric(evt.getKeyChar())) {
            txtProduitSeuil.setText(txtProduitSeuil.getText().replace(String.valueOf(evt.getKeyChar()),""));
        }
    }//GEN-LAST:event_txtProduitSeuilKeyReleased

    private void btProduitSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProduitSaveMouseEntered
        btProduitSave.setForeground(Color.red);
    }//GEN-LAST:event_btProduitSaveMouseEntered

    private void btProduitSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProduitSaveMouseExited
         btProduitSave.setForeground(btProduitReset.getForeground());
    }//GEN-LAST:event_btProduitSaveMouseExited

    private void btProduitResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProduitResetMouseEntered
         btProduitReset.setForeground(Color.red);
    }//GEN-LAST:event_btProduitResetMouseEntered

    private void btProduitResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProduitResetMouseExited
         btProduitReset.setForeground(btProduitSave.getForeground());
    }//GEN-LAST:event_btProduitResetMouseExited

    public void cbFamille() {
        Query qrFamille = em.createNamedQuery("Famille.findAll");
        List<Famille> listFamille = qrFamille.getResultList();
        cboFamille.removeAllItems();

        for (Famille famille : listFamille) {
            cboFamille.addItem(famille.getDesignation());
        }
        cboFamille.setSelectedIndex(-1);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btProduitReset;
    private javax.swing.JButton btProduitSave;
    private javax.swing.JComboBox cboFamille;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtProduitNom;
    private javax.swing.JTextField txtProduitPrixUnitaire;
    private javax.swing.JTextField txtProduitSeuil;
    // End of variables declaration//GEN-END:variables
}
