/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fenetre.Gestion;

import Entity.Parametrevente;
import Metier.Fichier;
import java.awt.Color;
import java.time.Instant;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import ridayasoft.Metier;

/**
 *
 * @author Gauss
 */
public class GestionTvaGainForm extends javax.swing.JPanel {

    /**
     * Creates new form AjusterTvaGain
     */
    EntityManagerFactory emf;
    EntityManager em;
    Metier metier = new Metier();
    String message = null;
    Parametrevente parametreVente = new Parametrevente();
    Parametrevente lastParametrevente;

    public GestionTvaGainForm() {
        initComponents();
        try {
            emf = Persistence.createEntityManagerFactory("RidayaSoftPU");
            em = emf.createEntityManager();
            bg.add(rbTva);
            bg.add(rbGain);

            Query qrParamVente = em.createNamedQuery("Parametrevente.findAll");
            List<Parametrevente> listParamVente = qrParamVente.getResultList();

            if (listParamVente.isEmpty()) {
                lastParametrevente = new Parametrevente();
                lastParametrevente.setGain(0);
                lastParametrevente.setTva(0);
            } else {
                lastParametrevente = listParamVente.get(listParamVente.size() - 1);

            }

            txtTva.setText("La valeur de taxe sur la valeur ajoutée : " + lastParametrevente.getTva() + " %");
            txtGain.setText("La valeur du gain : " + lastParametrevente.getGain() + " %");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btStockSave = new javax.swing.JButton();
        txtTvaGainValeur = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btStockReset = new javax.swing.JButton();
        rbTva = new javax.swing.JRadioButton();
        rbGain = new javax.swing.JRadioButton();
        txtTva = new javax.swing.JLabel();
        txtGain = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion : Gain et TVA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("Enregistrement : Gain & TVA");

        btStockSave.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btStockSave.setForeground(new java.awt.Color(0, 207, 255));
        btStockSave.setText("Valider");
        btStockSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 207, 255)));
        btStockSave.setContentAreaFilled(false);
        btStockSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btStockSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btStockSaveMouseExited(evt);
            }
        });
        btStockSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStockSaveActionPerformed(evt);
            }
        });

        txtTvaGainValeur.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtTvaGainValeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTvaGainValeurActionPerformed(evt);
            }
        });
        txtTvaGainValeur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTvaGainValeurKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("Nouvelle valeur : ");

        btStockReset.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btStockReset.setForeground(new java.awt.Color(0, 207, 255));
        btStockReset.setText("Reinitialiser");
        btStockReset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 207, 255)));
        btStockReset.setContentAreaFilled(false);
        btStockReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btStockResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btStockResetMouseExited(evt);
            }
        });
        btStockReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStockResetActionPerformed(evt);
            }
        });

        rbTva.setBackground(new java.awt.Color(255, 255, 255));
        rbTva.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        rbTva.setText("TVA");

        rbGain.setBackground(new java.awt.Color(255, 255, 255));
        rbGain.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        rbGain.setText("Gain");

        txtTva.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtTva.setText("La valeur de taxe sur la valeur ajoutée :   ");

        txtGain.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtGain.setText("La valeur du gain :   ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(btStockSave, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btStockReset, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel4)
                        .addGap(14, 14, 14)
                        .addComponent(txtTvaGainValeur, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(rbTva)
                        .addGap(18, 18, 18)
                        .addComponent(rbGain))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtTva))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtGain)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbTva)
                    .addComponent(rbGain))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTvaGainValeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btStockSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btStockReset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtTva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGain)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btStockSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStockSaveActionPerformed
        if (txtTvaGainValeur.getText().isEmpty() || (!rbGain.isSelected() && !rbTva.isSelected())) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir les champs vide !", "Ridaya Soft : Stock", JOptionPane.ERROR_MESSAGE);
        } else {
            try {

                if (rbTva.isSelected()) {

                    parametreVente.setTva(Integer.parseInt(txtTvaGainValeur.getText()));
                    parametreVente.setDateModif(Date.from(Instant.now()));
                    parametreVente.setGain(lastParametrevente.getGain());

                    message = "Parametre updater avec succes ! Le TVA est passé de " + lastParametrevente.getTva() + "% à " + txtTvaGainValeur.getText() + "%";
                    new Fichier().ecrireFichierLogAccess("Modification TVA à " + Date.from(Instant.now()));
                    txtTva.setText("La valeur de taxe sur la valeur ajoutée : " + txtTvaGainValeur.getText() + " %");
                } else if (rbGain.isSelected()) {
                    parametreVente.setTva(lastParametrevente.getTva());
                    parametreVente.setDateModif(Date.from(Instant.now()));
                    parametreVente.setGain(Integer.parseInt(txtTvaGainValeur.getText()));
                    message = "Parametre updater avec succes ! Le Gain est passé de " + lastParametrevente.getGain() + "% à " + txtTvaGainValeur.getText() + "%";
                    new Fichier().ecrireFichierLogAccess("Modification du gain à " + Date.from(Instant.now()));
                    txtGain.setText("La valeur du gain : " + txtTvaGainValeur.getText() + " %");
                }

                EntityTransaction transaction = em.getTransaction();
                transaction.begin();
                em.persist(parametreVente);
                transaction.commit();
                JOptionPane.showMessageDialog(null, message, "Ridaya Soft : Parametre Vente", JOptionPane.INFORMATION_MESSAGE);
                init();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_btStockSaveActionPerformed
    public void init() {
        txtTvaGainValeur.setText("");
    }
    private void txtTvaGainValeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTvaGainValeurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTvaGainValeurActionPerformed

    private void btStockResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStockResetActionPerformed
        init();
    }//GEN-LAST:event_btStockResetActionPerformed

    private void txtTvaGainValeurKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTvaGainValeurKeyReleased
        if (!metier.isNumeric(evt.getKeyChar())) {
            txtTvaGainValeur.setText(txtTvaGainValeur.getText().replace(String.valueOf(evt.getKeyChar()), ""));
        }
    }//GEN-LAST:event_txtTvaGainValeurKeyReleased

    private void btStockSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btStockSaveMouseEntered
        btStockSave.setForeground(Color.red);
    }//GEN-LAST:event_btStockSaveMouseEntered

    private void btStockSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btStockSaveMouseExited
        btStockSave.setForeground(btStockReset.getForeground());
    }//GEN-LAST:event_btStockSaveMouseExited

    private void btStockResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btStockResetMouseEntered
        btStockReset.setForeground(Color.red);
    }//GEN-LAST:event_btStockResetMouseEntered

    private void btStockResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btStockResetMouseExited
        btStockReset.setForeground(btStockSave.getForeground());
    }//GEN-LAST:event_btStockResetMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg;
    private javax.swing.JButton btStockReset;
    private javax.swing.JButton btStockSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbGain;
    private javax.swing.JRadioButton rbTva;
    private javax.swing.JLabel txtGain;
    private javax.swing.JLabel txtTva;
    private javax.swing.JTextField txtTvaGainValeur;
    // End of variables declaration//GEN-END:variables
}
