/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fenetre;

import Fenetre.Dette.SolderDetteForm;
import Fenetre.Dette.PretDetteForm;
import Fenetre.Dette.RemboursementDetteForm;
import Fenetre.Dette.InsolvableDetteForm;
import Metier.Fichier;
import java.awt.Color;

/**
 *
 * @author Gauss
 */
public class DetteForm extends javax.swing.JPanel {

    /**
     * Creates new form AdminForm
     */
    public DetteForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btPret = new javax.swing.JButton();
        btRemboursement = new javax.swing.JButton();
        btInsolvable = new javax.swing.JButton();
        btDetteSolder = new javax.swing.JButton();
        jspBidon = new javax.swing.JScrollPane();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 207, 255));
        jLabel1.setText("Gestion Dette");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(250, 250, 250));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel4.setPreferredSize(new java.awt.Dimension(310, 45));

        btPret.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btPret.setText("Prêt");
        btPret.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 207, 255), 2));
        btPret.setContentAreaFilled(false);
        btPret.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btPretMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btPretMouseExited(evt);
            }
        });
        btPret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPretActionPerformed(evt);
            }
        });

        btRemboursement.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btRemboursement.setText("Remboursement");
        btRemboursement.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 207, 255), 2));
        btRemboursement.setContentAreaFilled(false);
        btRemboursement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btRemboursementMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btRemboursementMouseExited(evt);
            }
        });
        btRemboursement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemboursementActionPerformed(evt);
            }
        });

        btInsolvable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btInsolvable.setText("Insolvable");
        btInsolvable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 207, 255), 2));
        btInsolvable.setContentAreaFilled(false);
        btInsolvable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btInsolvableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btInsolvableMouseExited(evt);
            }
        });
        btInsolvable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsolvableActionPerformed(evt);
            }
        });

        btDetteSolder.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btDetteSolder.setText("Dette soldée");
        btDetteSolder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 207, 255), 2));
        btDetteSolder.setContentAreaFilled(false);
        btDetteSolder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btDetteSolderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btDetteSolderMouseExited(evt);
            }
        });
        btDetteSolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDetteSolderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btPret, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(btRemboursement, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(btInsolvable, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btDetteSolder, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btRemboursement, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btPret, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btInsolvable, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btDetteSolder, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jspBidon.setBackground(new java.awt.Color(255, 255, 255));
        jspBidon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 233, 233)));
        jspBidon.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
            .addComponent(jspBidon)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jspBidon, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btPretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPretActionPerformed
        jspBidon.setViewportView(new PretDetteForm());
        new Fichier().ecrireFichierLogAccess("Click sur pret!");
    }//GEN-LAST:event_btPretActionPerformed

    private void btRemboursementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemboursementActionPerformed
       jspBidon.setViewportView(new RemboursementDetteForm());
       new Fichier().ecrireFichierLogAccess("Click sur Remboursement dette !");
    }//GEN-LAST:event_btRemboursementActionPerformed

    private void btPretMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPretMouseEntered
        btPret.setForeground(Color.red);
    }//GEN-LAST:event_btPretMouseEntered

    private void btPretMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPretMouseExited
        btPret.setForeground(Color.BLACK);
    }//GEN-LAST:event_btPretMouseExited

    private void btRemboursementMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRemboursementMouseEntered
        btRemboursement.setForeground(Color.red);
    }//GEN-LAST:event_btRemboursementMouseEntered

    private void btRemboursementMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRemboursementMouseExited
        btRemboursement.setForeground(Color.BLACK);
    }//GEN-LAST:event_btRemboursementMouseExited

    private void btInsolvableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btInsolvableMouseEntered
        btInsolvable.setForeground(Color.red);
    }//GEN-LAST:event_btInsolvableMouseEntered

    private void btInsolvableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btInsolvableMouseExited
        btInsolvable.setForeground(Color.BLACK);
    }//GEN-LAST:event_btInsolvableMouseExited

    private void btInsolvableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsolvableActionPerformed
        jspBidon.setViewportView(new InsolvableDetteForm());
        new Fichier().ecrireFichierLogAccess("Click sur Bouton Insolvable !");
    }//GEN-LAST:event_btInsolvableActionPerformed

    private void btDetteSolderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDetteSolderMouseEntered
        btDetteSolder.setForeground(Color.red);
    }//GEN-LAST:event_btDetteSolderMouseEntered

    private void btDetteSolderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDetteSolderMouseExited
       btDetteSolder.setForeground(Color.BLACK);
    }//GEN-LAST:event_btDetteSolderMouseExited

    private void btDetteSolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDetteSolderActionPerformed
        jspBidon.setViewportView(new SolderDetteForm());
        new Fichier().ecrireFichierLogAccess("Click sur bouton DetteSolder !");
    }//GEN-LAST:event_btDetteSolderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDetteSolder;
    private javax.swing.JButton btInsolvable;
    private javax.swing.JButton btPret;
    private javax.swing.JButton btRemboursement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JScrollPane jspBidon;
    // End of variables declaration//GEN-END:variables
}
