/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fenetre;

import Entity.Client;
import Entity.Commander;
import Entity.Facture;
import Entity.Produit;
import Entity.User;
import Metier.ClientMetier;
import Metier.ConnexionBD;
import Metier.FactureMetier;
import Metier.Fichier;
import Metier.IReport;
import Metier.ProduitMetier;
import Metier.StockMetier;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ridayasoft.Metier;

/**
 *
 * @author Gauss
 */
public class VenteForm extends javax.swing.JPanel {

    /**
     * Creates new form VenteForm
     */
    EntityManagerFactory emf;
    EntityManager em;
    Produit idProduit;
    Client idClient;
    Metier metier = new Metier();
    double netApayerTotal = 0;
    int nombreCommande = 0;
    DefaultTableModel model;
    ClientMetier clientMetier = new ClientMetier();

    public VenteForm() {
        initComponents();
        model = (DefaultTableModel) tbFacture.getModel();
        tbFacture.setComponentPopupMenu(jPopupMenu1);
        try {
//            emf = Persistence.createEntityManagerFactory("RidayaSoftPU");
            em = new ConnexionBD().getConnexion();
            new ProduitMetier().cboProduit(em, cbProduit);
            new ClientMetier().cboClient(em, cbClientNom);
            txtFactureId.setText(String.valueOf(new FactureMetier().idFacture(em)));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtFactureId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtClientPrenom = new javax.swing.JTextField();
        cbClientNom = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbProduit = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtCommandeQuantite = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEtatStock = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPrixVente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPrixTotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtRemise = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtNetAPayer = new javax.swing.JTextField();
        btSavePanier = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFacture = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btFactureSave = new javax.swing.JButton();
        btCommandeDelete = new javax.swing.JButton();
        btFactureInit = new javax.swing.JButton();
        btFacturePrint = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        setPreferredSize(new java.awt.Dimension(907, 547));

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setPreferredSize(new java.awt.Dimension(907, 537));

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 207, 255));
        jLabel1.setText("Ventes : Facturation");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Facture");

        txtFactureId.setEditable(false);
        txtFactureId.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtFactureId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFactureIdActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel3.setText("N° Facture : ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel4.setText("Nom du client : ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel5.setText("Prenom du client :");

        txtClientPrenom.setEditable(false);
        txtClientPrenom.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        cbClientNom.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbClientNomPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cbClientNomPopupMenuWillBecomeVisible(evt);
            }
        });

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtClientPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(cbClientNom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtFactureId, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFactureId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbClientNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtClientPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Produits");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel7.setText("Produit : ");

        cbProduit.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cbProduit.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbProduitPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel8.setText("Quantité : ");

        txtCommandeQuantite.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtCommandeQuantite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCommandeQuantiteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCommandeQuantiteKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel9.setText("Etat stock : ");

        txtEtatStock.setEditable(false);
        txtEtatStock.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel10.setText("Prix de vente :");

        txtPrixVente.setEditable(false);
        txtPrixVente.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel11.setText("Prix total :");

        txtPrixTotal.setEditable(false);
        txtPrixTotal.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel12.setText("Remise : ");

        txtRemise.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtRemise.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRemiseKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel13.setText("Net à payer :");

        txtNetAPayer.setEditable(false);
        txtNetAPayer.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        btSavePanier.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btSavePanier.setText("Ajouter au panier");
        btSavePanier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btSavePanier.setContentAreaFilled(false);
        btSavePanier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSavePanierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSavePanierMouseExited(evt);
            }
        });
        btSavePanier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSavePanierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(cbProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addComponent(txtCommandeQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(116, 116, 116)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtPrixVente, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addComponent(txtEtatStock, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNetAPayer)
                            .addComponent(txtPrixTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRemise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSavePanier, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtPrixTotal, txtRemise});

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCommandeQuantite, txtEtatStock, txtPrixVente});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbProduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCommandeQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtPrixTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtEtatStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtRemise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPrixVente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtNetAPayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btSavePanier, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setAutoscrolls(true);

        tbFacture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(39, 175, 201)));
        tbFacture.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tbFacture.setForeground(new java.awt.Color(60, 60, 60));
        tbFacture.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro", "Réf Produit", "Désignation", "Quantité", "Prix unitaire", "Prix total", "Remise", "Net à payer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbFacture.setGridColor(new java.awt.Color(39, 175, 201));
        tbFacture.getTableHeader().setResizingAllowed(false);
        tbFacture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbFactureMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbFacture);

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("Panier de produits selectionnés");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        btFactureSave.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btFactureSave.setText("Enregistrer");
        btFactureSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(39, 175, 201), 2));
        btFactureSave.setContentAreaFilled(false);
        btFactureSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btFactureSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btFactureSaveMouseExited(evt);
            }
        });
        btFactureSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFactureSaveActionPerformed(evt);
            }
        });

        btCommandeDelete.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btCommandeDelete.setText("Supprimer");
        btCommandeDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(39, 175, 201), 2));
        btCommandeDelete.setContentAreaFilled(false);
        btCommandeDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btCommandeDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btCommandeDeleteMouseExited(evt);
            }
        });
        btCommandeDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCommandeDeleteActionPerformed(evt);
            }
        });

        btFactureInit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btFactureInit.setText("Réinitialiser");
        btFactureInit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(39, 175, 201), 2));
        btFactureInit.setContentAreaFilled(false);
        btFactureInit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btFactureInitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btFactureInitMouseExited(evt);
            }
        });
        btFactureInit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFactureInitActionPerformed(evt);
            }
        });

        btFacturePrint.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btFacturePrint.setText("Imprimer");
        btFacturePrint.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(39, 175, 201), 2));
        btFacturePrint.setContentAreaFilled(false);
        btFacturePrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btFacturePrintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btFacturePrintMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btFactureSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btCommandeDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btFactureInit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btFacturePrint, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btFacturePrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCommandeDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btFactureInit, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                    .addComponent(btFactureSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSeparator2)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(483, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFactureIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFactureIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFactureIdActionPerformed
    List<Commander> listCommande = new ArrayList<>();
    private void btSavePanierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSavePanierActionPerformed
        ajoutPanier();
    }//GEN-LAST:event_btSavePanierActionPerformed
    private void ajoutPanier() {
        try {
            
            if (Integer.parseInt(txtCommandeQuantite.getText()) > Integer.parseInt(txtEtatStock.getText())) {
                JOptionPane.showMessageDialog(null, "La quantité commandé est superieure à la quatité disponible dans le stock !", "RidayaSoft : Facturation", JOptionPane.ERROR_MESSAGE);

            } else if (cbProduit.getSelectedIndex() == -1 || cbProduit.getSelectedItem().toString().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Veuillez choisir le produit !", "RidayaSoft : Facturation", JOptionPane.ERROR_MESSAGE);
            } else if (Integer.parseInt(txtCommandeQuantite.getText()) < 1) {
                JOptionPane.showMessageDialog(null, "Veuillez introduire la quantité existante !", "RidayaSoft : Facturation", JOptionPane.ERROR_MESSAGE);
            } 
            else if ( Double.parseDouble(txtRemise.getText()) > Double.parseDouble(txtPrixTotal.getText())) {
                JOptionPane.showMessageDialog(null, "La remise est superieur au montant payé !", "RidayaSoft : Facturation", JOptionPane.ERROR_MESSAGE);
            } 
            else {
                Commander commande = new Commander();
                commande.setDateCommander(Date.from(Instant.now()));
                commande.setPrixVenteCommander(Double.parseDouble(txtPrixVente.getText()));
                commande.setIdProduit(idProduit);
                commande.setQuantiteCommander(Integer.parseInt(txtCommandeQuantite.getText()));
                commande.setRemiseCommander(Double.parseDouble(txtRemise.getText()));
                listCommande.add(commande);

                // Table
                model.insertRow(model.getRowCount(), new Object[]{
                    listCommande.size(),
                    idProduit.getIdProduit(),
                    idProduit.getNomProduit(),
                    Integer.parseInt(txtCommandeQuantite.getText()),
                    idProduit.getPrixUnitaire(),
                    (Integer.parseInt(txtCommandeQuantite.getText()) * idProduit.getPrixUnitaire()),
                    Integer.parseInt(txtRemise.getText()),
                   ((Integer.parseInt(txtCommandeQuantite.getText()) * idProduit.getPrixUnitaire()) - Integer.parseInt(txtRemise.getText()))});

                netApayerTotal = netApayerTotal + Double.parseDouble(txtNetAPayer.getText());

                cbProduit.setSelectedIndex(-1);
                txtCommandeQuantite.setText("");
                txtEtatStock.setText("");
                txtNetAPayer.setText("");
                txtPrixTotal.setText("");
                txtRemise.setText("");
                txtPrixVente.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur : Produit non ajouter au panier ! " + e.getMessage(), "Ridaya Soft : Vente", JOptionPane.ERROR_MESSAGE);
        }
    }
    double netApayer = 0;
    private void cbProduitPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbProduitPopupMenuWillBecomeInvisible
        try {
            txtCommandeQuantite.setText("");
            txtEtatStock.setText("");
            txtPrixVente.setText("");
            txtPrixTotal.setText("");
            txtRemise.setText("");

            ProduitMetier produitMetier = new ProduitMetier();
            idProduit = produitMetier.produitParNom(em, cbProduit.getSelectedItem().toString());

            // Etat de stock
            txtEtatStock.setText(new StockMetier().etatDeStockParProduit(em, idProduit.getIdProduit()).get(0).toString());
            // Pour prix de vente
            txtPrixVente.setText(String.valueOf(idProduit.getPrixUnitaire()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur : Aucun produit choisi !", "Ridaya Soft : Vente", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cbProduitPopupMenuWillBecomeInvisible

    private void txtCommandeQuantiteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCommandeQuantiteKeyReleased
        if (!metier.isNumeric(evt.getKeyChar())) {
            txtCommandeQuantite.setText(txtCommandeQuantite.getText().replace(String.valueOf(evt.getKeyChar()), ""));
        }

        try {
            // Prix total
            double prixTotal = Double.parseDouble(txtCommandeQuantite.getText()) * Double.parseDouble(txtPrixVente.getText());
            txtPrixTotal.setText(String.valueOf(prixTotal));
            txtNetAPayer.setText(String.valueOf(prixTotal));
            txtRemise.setText("0");
        } catch (Exception e) {
        }


    }//GEN-LAST:event_txtCommandeQuantiteKeyReleased

    private void btFactureSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFactureSaveActionPerformed
        if (listCommande.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Aucune commande n'a été faite ! ", "RidayaSoft : Facturation", JOptionPane.ERROR_MESSAGE);

        } else if (cbClientNom.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Verifier le nom du client !", "RidayaSoft : Facturation", JOptionPane.ERROR_MESSAGE);

        } else {

//            Client client = new Client();
//            client.setNomClient(txtClientNom.getText());
//            client.setPrenomClient(txtClientPrenom.getText());
            // Facture
            Facture facture = new Facture();
            facture.setDateFacture(Date.from(Instant.now()));
            facture.setIdClient(idClient);
           // facture.setRemiseFacture(Double.parseDouble(txtRemise.getText()));

            User user = new User();
            user.setIdUser(Integer.parseInt(new Fichier().lireFichier().trim()));
            facture.setIdUser(user);
            EntityTransaction transaction = em.getTransaction();
            try {

                transaction.begin();
//                em.persist(idClient);
                em.persist(facture);
                transaction.commit();
//        JOptionPane.showMessageDialog(null, client.getIdClient());
                for (Commander onlyCommande : listCommande) {
                    onlyCommande.setIdProduit(onlyCommande.getIdProduit());
                    onlyCommande.setIdClient(idClient);

                    transaction.begin();
                    em.persist(onlyCommande);
                    transaction.commit();
                    nombreCommande++;
                }

                JOptionPane.showMessageDialog(null, "Commande du client " + cbClientNom.getSelectedItem().toString().toUpperCase() + " a été enregistrer!", "RidayaSoft : Facturation", JOptionPane.INFORMATION_MESSAGE);
//                int nouvelleFacture = Integer.parseInt(txtFactureId.getText()) + 1;
                txtFactureId.setText(String.valueOf(Integer.parseInt(txtFactureId.getText()) + 1));

                new Fichier().ecrireFichierLogAccess("Enregistrement de la vente du client " + cbClientNom.getSelectedItem().toString() + " à " + Date.from(Instant.now()));

                int printFacture = JOptionPane.showConfirmDialog(null, "Voulez vous imprimer la facture?", "RidayaSoft : Facture", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (printFacture == JOptionPane.YES_OPTION) {
                    String ss = getClass().getResource("/Report/FactureStatique.jrxml").toString();
//                  new IReport().reportStatique("C:\\Users\\Gauss\\Documents\\NetBeansProjects\\RidayaSoft\\Rapport\\FactureStatique.jrxml");
                    // JOptionPane.showMessageDialog(null, );
                    new IReport().reportStatique(ss.replace("file:/", ""));
                } else {
                    JOptionPane.showMessageDialog(null, "Le client " + cbClientNom.getSelectedItem().toString().toUpperCase() + " doit payer " + netApayerTotal + " Fc!", "RidayaSoft : Facturation", JOptionPane.INFORMATION_MESSAGE);
                }
                init();
            } catch (Exception e) {
                new ClientMetier().suppLastId(em);
                JOptionPane.showMessageDialog(null, "Deux ou plusieurs produits du meme nom sur le panier : Sommer les produits ayant le même nom !");
                init();
            }
        }
    }//GEN-LAST:event_btFactureSaveActionPerformed
    public void init() {
        txtClientPrenom.setText("");
        txtCommandeQuantite.setText("");
        txtEtatStock.setText("");
        txtNetAPayer.setText("");
        txtPrixTotal.setText("");
        txtPrixVente.setText("");
        txtRemise.setText("");
        cbProduit.setSelectedIndex(-1);
        cbClientNom.setSelectedIndex(-1);
        listCommande.clear();
        new Metier().supTab(model);
        netApayerTotal = 0;
    }
    private void txtCommandeQuantiteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCommandeQuantiteKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ajoutPanier();
        }
    }//GEN-LAST:event_txtCommandeQuantiteKeyPressed

    private void tbFactureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFactureMouseClicked
        cbProduit.setSelectedItem(String.valueOf(model.getValueAt(tbFacture.getSelectedRow(), 2)));
        txtCommandeQuantite.setText(String.valueOf(model.getValueAt(tbFacture.getSelectedRow(), 3)));
        txtPrixVente.setText(String.valueOf(model.getValueAt(tbFacture.getSelectedRow(), 4)));
        txtPrixTotal.setText(String.valueOf(model.getValueAt(tbFacture.getSelectedRow(), 5)));
        txtNetAPayer.setText(String.valueOf(model.getValueAt(tbFacture.getSelectedRow(), 7)));
        txtRemise.setText(String.valueOf(model.getValueAt(tbFacture.getSelectedRow(), 6)));

        // Etat de stock
        txtEtatStock.setText(new StockMetier().etatDeStockParProduit(em, idProduit.getIdProduit()).get(0).toString());
    }//GEN-LAST:event_tbFactureMouseClicked

    private void btSavePanierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSavePanierMouseEntered
        btSavePanier.setForeground(Color.red);
    }//GEN-LAST:event_btSavePanierMouseEntered

    private void btSavePanierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSavePanierMouseExited
        btSavePanier.setForeground(Color.black);
    }//GEN-LAST:event_btSavePanierMouseExited

    private void btFactureSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFactureSaveMouseEntered
        btFactureSave.setForeground(Color.red);
    }//GEN-LAST:event_btFactureSaveMouseEntered

    private void btFactureSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFactureSaveMouseExited
        btFactureSave.setForeground(Color.black);
    }//GEN-LAST:event_btFactureSaveMouseExited

    private void btCommandeDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCommandeDeleteMouseEntered
        btCommandeDelete.setForeground(Color.red);
    }//GEN-LAST:event_btCommandeDeleteMouseEntered

    private void btCommandeDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCommandeDeleteMouseExited
        btCommandeDelete.setForeground(Color.black);
    }//GEN-LAST:event_btCommandeDeleteMouseExited

    private void btFactureInitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFactureInitMouseEntered
        btFactureInit.setForeground(Color.red);
    }//GEN-LAST:event_btFactureInitMouseEntered

    private void btFactureInitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFactureInitMouseExited
        btFactureInit.setForeground(Color.black);
    }//GEN-LAST:event_btFactureInitMouseExited

    private void btFacturePrintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFacturePrintMouseEntered
        btFacturePrint.setForeground(Color.red);
    }//GEN-LAST:event_btFacturePrintMouseEntered

    private void btFacturePrintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFacturePrintMouseExited
        btFacturePrint.setForeground(Color.black);
    }//GEN-LAST:event_btFacturePrintMouseExited

    private void btCommandeDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCommandeDeleteActionPerformed
//       JOptionPane.showMessageDialog(null, tbFacture.getSelectedRow());
        listCommande.remove(tbFacture.getSelectedRow());
        model.removeRow(tbFacture.getSelectedRow());

    }//GEN-LAST:event_btCommandeDeleteActionPerformed

    private void btFactureInitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFactureInitActionPerformed
        init();
        listCommande.clear();
        for (int i = model.getRowCount() - 1; i > -1; i--) {
            model.removeRow(i);
        }

    }//GEN-LAST:event_btFactureInitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Fenetre.Client.Client clientForm = new Fenetre.Client.Client(null, true);
        clientForm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbClientNomPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbClientNomPopupMenuWillBecomeInvisible
        try {
            idClient = clientMetier.clientParNom(em, cbClientNom.getSelectedItem().toString());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cbClientNomPopupMenuWillBecomeInvisible

    private void txtRemiseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRemiseKeyReleased
        if (!metier.isNumeric(evt.getKeyChar())) {
            txtRemise.setText(txtRemise.getText().replace(String.valueOf(evt.getKeyChar()), ""));
        }
        
        try {
            // Prix total Net a payé
            double prixNetApayer = Double.parseDouble(txtPrixTotal.getText()) - Double.parseDouble(txtRemise.getText());
            txtNetAPayer.setText(String.valueOf(prixNetApayer));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtRemiseKeyReleased

    private void cbClientNomPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbClientNomPopupMenuWillBecomeVisible
        try {
            cbClientNom.removeAllItems();
            new ClientMetier().cboClient(em, cbClientNom);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_cbClientNomPopupMenuWillBecomeVisible


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCommandeDelete;
    private javax.swing.JButton btFactureInit;
    private javax.swing.JButton btFacturePrint;
    private javax.swing.JButton btFactureSave;
    private javax.swing.JButton btSavePanier;
    private javax.swing.JComboBox cbClientNom;
    private javax.swing.JComboBox cbProduit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tbFacture;
    private javax.swing.JTextField txtClientPrenom;
    private javax.swing.JTextField txtCommandeQuantite;
    private javax.swing.JTextField txtEtatStock;
    private javax.swing.JTextField txtFactureId;
    private javax.swing.JTextField txtNetAPayer;
    private javax.swing.JTextField txtPrixTotal;
    private javax.swing.JTextField txtPrixVente;
    private javax.swing.JTextField txtRemise;
    // End of variables declaration//GEN-END:variables
}
