/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fenetre.Comptabilite;

import Metier.ConnexionBD;
import Metier.Fichier;
import Metier.IReport;
import Metier.StockMetier;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ridayasoft.Metier;

/**
 *
 * @author Gauss
 */
public class ClotureJournalierForm extends javax.swing.JPanel {

    /**
     * Creates new form ClotureJournalierForm
     */
    EntityManagerFactory emf;
    EntityManager em;
    DefaultTableModel model;
    StockMetier stockMetier = new StockMetier();
    Metier metier = new Metier();
    String dateJour = null;

    public ClotureJournalierForm() {
        initComponents();
        model = (DefaultTableModel) tbVenteJournaliere.getModel();
//        
        try {
            
            em = new ConnexionBD().getConnexion();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        dateJour = metier.dateCourante();
        venteJournaliere(metier.dateCourante());

    }

    public void venteJournaliere(String date) {
        try {
            List listFacture = stockMetier.venteJournaliere(em, date);

            for (Object facture : listFacture) {
                Object[] factureTab = (Object[]) facture;
                model.insertRow(model.getRowCount(), new Object[]{factureTab[0], factureTab[1], factureTab[2], factureTab[3]});

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dtClotureJour = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVenteJournaliere = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cloture journalière");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel2.setText("Jour : ");

        dtClotureJour.setDateFormatString("yyyy-MM-dd");
        dtClotureJour.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        dtClotureJour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtClotureJourMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dtClotureJourMouseReleased(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);

        tbVenteJournaliere.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(39, 175, 201)));
        tbVenteJournaliere.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tbVenteJournaliere.setForeground(new java.awt.Color(60, 60, 60));
        tbVenteJournaliere.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num Facture", "Nom du client", "Montant total", "Date facturation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbVenteJournaliere.setGridColor(new java.awt.Color(39, 175, 201));
        tbVenteJournaliere.setInheritsPopupMenu(true);
        tbVenteJournaliere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbVenteJournaliereMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbVenteJournaliere);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 207, 255));
        jButton1.setText("Imprimer");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 207, 255), 2));
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 207, 255));
        jButton2.setText("Rechercher");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 207, 255), 2));
        jButton2.setContentAreaFilled(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dtClotureJour, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(dtClotureJour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setForeground(Color.red);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setForeground(Color.cyan);
    }//GEN-LAST:event_jButton1MouseExited

    private void dtClotureJourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtClotureJourMouseClicked

    }//GEN-LAST:event_dtClotureJourMouseClicked

    private void dtClotureJourMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtClotureJourMouseReleased

    }//GEN-LAST:event_dtClotureJourMouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
//        String date = sdf.format(dtClotureJour.getDate());
//        JOptionPane.showMessageDialog(null, date);
//        model.rowsRemoved(tbVenteJournaliere.);
        
        String lienReport = getClass().getResource("/Report/VenteJournaliereReport.jrxml").toString().replace("file:/", "");
        String sql = "SELECT facture.idFacture, client.nomClient, SUM(commander.prixVenteCommande * commander.quantiteCommande) AS Montant, facture.dateFacture " 
                        + "FROM facture " 
                        + "INNER JOIN client ON facture.idClient = client.idClient " 
                        + "INNER JOIN commander ON commander.idClient = client.idClient " 
                        + "INNER JOIN produit ON produit.idProduit = commander.idProduit " 
                        + "WHERE facture.dateFacture LIKE '"+dateJour+"%'" 
                        + "GROUP BY facture.idFacture, client.nomClient, facture.dateFacture";
        
        int printFacture = JOptionPane.showConfirmDialog(null, "Voulez vous imprimer la vente journalière?", "RidayaSoft : Vente Journalière", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (printFacture == JOptionPane.YES_OPTION) {
                    try {
                         new IReport().reportDynamique(lienReport, sql);
                     new Fichier().ecrireFichierLogAccess("Impression de la cloture journaliere "+ " à " + Date.from(Instant.now()));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Erreur rapport : "+ e);
                    }
                    
                   
                }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            
        
        if(dtClotureJour.getDate().toString().isEmpty()){
        JOptionPane.showMessageDialog(null, "Pas de date choisi ! ", "RidayaSoft : Clôture journalière", JOptionPane.ERROR_MESSAGE);
        } else {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(dtClotureJour.getDate());
        dateJour = date;
        if(model.getRowCount() > 0){
            for (int i = model.getRowCount() - 1; i > -1; i--) {
                model.removeRow(i);
            }
        }
        venteJournaliere(date);
      }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Date inconnu : Verifie la date de recherche", "RidayaSoft : Clôture journalière", JOptionPane.ERROR_MESSAGE);
        venteJournaliere(metier.dateCourante());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbVenteJournaliereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbVenteJournaliereMouseClicked
   if (evt.getClickCount() == 2) {
            SuppressionArticle d = new SuppressionArticle(null, true);
            d.txtNumFacture.setText(String.valueOf(model.getValueAt(tbVenteJournaliere.getSelectedRow(), 0)));
            d.setVisible(true);
        }
    }//GEN-LAST:event_tbVenteJournaliereMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dtClotureJour;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbVenteJournaliere;
    // End of variables declaration//GEN-END:variables
}
