/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fenetre.Bidon;

import Entity.Bidon;
import Metier.Fichier;
import java.awt.Color;
import java.time.Instant;
import java.util.Date;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import ridayasoft.Metier;

/**
 *
 * @author Gauss
 */
public class CreationTypeBidonForm extends javax.swing.JPanel {

    /**
     * Creates new form GestionUserForm
     */
    EntityManagerFactory emf;
    EntityManager em;
    Metier metier = new Metier();
    Bidon idBidon;
    
    public CreationTypeBidonForm() {
        initComponents();
        try {
            emf = Persistence.createEntityManagerFactory("RidayaSoftPU");
            em = emf.createEntityManager();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btStockBidonSave = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btUserReset = new javax.swing.JButton();
        txtTypeBidon = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Création : Stock Bidon");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Enregistrement :Bidon");

        btStockBidonSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btStockBidonSave.setForeground(new java.awt.Color(0, 207, 255));
        btStockBidonSave.setText("Valider");
        btStockBidonSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 207, 255)));
        btStockBidonSave.setContentAreaFilled(false);
        btStockBidonSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btStockBidonSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btStockBidonSaveMouseExited(evt);
            }
        });
        btStockBidonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStockBidonSaveActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel8.setText("Type de Bidon :");

        btUserReset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btUserReset.setForeground(new java.awt.Color(0, 207, 255));
        btUserReset.setText("Reinitialiser");
        btUserReset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 207, 255)));
        btUserReset.setContentAreaFilled(false);
        btUserReset.setPreferredSize(new java.awt.Dimension(57, 35));
        btUserReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btUserResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btUserResetMouseExited(evt);
            }
        });
        btUserReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUserResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btStockBidonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btUserReset, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel8)
                        .addGap(84, 84, 84)
                        .addComponent(txtTypeBidon, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(47, 47, 47)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTypeBidon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btStockBidonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btUserReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btStockBidonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStockBidonSaveActionPerformed
        
        if (txtTypeBidon.getText().length() < 1) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir les champs vide", "Ridaya Soft : Bidon", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Bidon bidon = new Bidon();
                bidon.setTypeBidon(txtTypeBidon.getText());
                EntityTransaction transaction = em.getTransaction();
                transaction.begin();
                em.persist(bidon);
                transaction.commit();
                JOptionPane.showMessageDialog(null, "Type bidon ajouté avec succes !", "Ridaya Soft : Bidon", JOptionPane.INFORMATION_MESSAGE);
                new Fichier().ecrireFichierLogAccess("Creation de type bidon " + txtTypeBidon.getText() + " à " + Date.from(Instant.now()));
                init();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Ce type de bidon existe déjà !", "Ridaya Soft : Bidon", JOptionPane.ERROR_MESSAGE);
            } 
        }
    }//GEN-LAST:event_btStockBidonSaveActionPerformed
    public void init() {
        txtTypeBidon.setText("");
    }
    private void btUserResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUserResetActionPerformed
        init();
    }//GEN-LAST:event_btUserResetActionPerformed

    private void btStockBidonSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btStockBidonSaveMouseEntered
        btStockBidonSave.setForeground(Color.red);
    }//GEN-LAST:event_btStockBidonSaveMouseEntered

    private void btStockBidonSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btStockBidonSaveMouseExited
        btStockBidonSave.setForeground(btUserReset.getForeground());
    }//GEN-LAST:event_btStockBidonSaveMouseExited

    private void btUserResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btUserResetMouseEntered
        btUserReset.setForeground(Color.red);
    }//GEN-LAST:event_btUserResetMouseEntered

    private void btUserResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btUserResetMouseExited
        btUserReset.setForeground(btStockBidonSave.getForeground());
    }//GEN-LAST:event_btUserResetMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btStockBidonSave;
    private javax.swing.JButton btUserReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField txtTypeBidon;
    // End of variables declaration//GEN-END:variables
}
