/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fenetre.Bidon;

import Entity.Bidon;
import Entity.Client;
import Entity.Emprunter;
import Metier.BidonMetier;
import Metier.ClientMetier;
import Metier.Fichier;
import Metier.StockMetier;
import java.awt.Color;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ridayasoft.Metier;

/**
 *
 * @author Gauss
 */
public class EmpruntBidonForm extends javax.swing.JPanel {

    /**
     * Creates new form GestionUserForm
     */
    EntityManagerFactory emf;
    EntityManager em;
    Metier metier = new Metier();
    Bidon idBidon;
    DefaultTableModel model;
    int nombreEmprunt = 0;
    Client idClient;
    ClientMetier clientMetier = new ClientMetier();

    public EmpruntBidonForm() {
        initComponents();
        model = (DefaultTableModel) tbEmpruntBidon.getModel();
        try {
            emf = Persistence.createEntityManagerFactory("RidayaSoftPU");
            em = emf.createEntityManager();
//            lblQtDispoTypeBidon.setVisible(false);
            cbClient();
            cbTypeBidon();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    public void cbClient() {
        Query qrClient = em.createNamedQuery("Client.findAll");
        List<Client> listClient = qrClient.getResultList();
        cbClientNom.removeAllItems();

        for (Client client : listClient) {
            cbClientNom.addItem(client.getNomClient());
        }
        cbClientNom.setSelectedIndex(-1);
    }

    public void cbTypeBidon() {
        Query qrBidon = em.createNamedQuery("Bidon.findAll");
        List<Bidon> listBidon = qrBidon.getResultList();
        cbTypeBidonEmprunt.removeAllItems();
        for (Bidon bidon : listBidon) {
            cbTypeBidonEmprunt.addItem(bidon.getTypeBidon());
        }
        cbTypeBidonEmprunt.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btStockBidonSave = new javax.swing.JButton();
        btUserReset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtQtBidonEmprunter = new javax.swing.JTextField();
        cbTypeBidonEmprunt = new javax.swing.JComboBox();
        btSavePanier = new javax.swing.JButton();
        lblQtDispoTypeBidon = new javax.swing.JLabel();
        txtQtDispoTypeBidon = new javax.swing.JTextField();
        cbClientNom = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEmpruntBidon = new javax.swing.JTable();
        btCommandeDelete = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Emprunt Bidon");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Emprunt :Bidon");

        btStockBidonSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btStockBidonSave.setForeground(new java.awt.Color(0, 207, 255));
        btStockBidonSave.setText("Valider");
        btStockBidonSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 207, 255)));
        btStockBidonSave.setContentAreaFilled(false);
        btStockBidonSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btStockBidonSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btStockBidonSaveMouseExited(evt);
            }
        });
        btStockBidonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStockBidonSaveActionPerformed(evt);
            }
        });

        btUserReset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btUserReset.setForeground(new java.awt.Color(0, 207, 255));
        btUserReset.setText("Reinitialiser");
        btUserReset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 207, 255)));
        btUserReset.setContentAreaFilled(false);
        btUserReset.setPreferredSize(new java.awt.Dimension(57, 35));
        btUserReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btUserResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btUserResetMouseExited(evt);
            }
        });
        btUserReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUserResetActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setText("Nom Client : ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel3.setText("Type bidon : ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel8.setText("Quantité empruntée :");

        txtQtBidonEmprunter.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtQtBidonEmprunter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtBidonEmprunterKeyReleased(evt);
            }
        });

        cbTypeBidonEmprunt.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cbTypeBidonEmprunt.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbTypeBidonEmpruntPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        btSavePanier.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btSavePanier.setText("Ajouter au panier");
        btSavePanier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btSavePanier.setContentAreaFilled(false);
        btSavePanier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSavePanierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSavePanierMouseExited(evt);
            }
        });
        btSavePanier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSavePanierActionPerformed(evt);
            }
        });

        lblQtDispoTypeBidon.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblQtDispoTypeBidon.setForeground(new java.awt.Color(255, 0, 0));
        lblQtDispoTypeBidon.setText("Quantité disponible :");

        txtQtDispoTypeBidon.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtQtDispoTypeBidon.setEnabled(false);
        txtQtDispoTypeBidon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtDispoTypeBidonKeyReleased(evt);
            }
        });

        cbClientNom.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cbClientNom.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbClientNomPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btSavePanier, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblQtDispoTypeBidon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtQtDispoTypeBidon, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtQtBidonEmprunter, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbClientNom, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbTypeBidonEmprunt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbClientNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbTypeBidonEmprunt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQtBidonEmprunter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtDispoTypeBidon)
                    .addComponent(txtQtDispoTypeBidon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSavePanier, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbEmpruntBidon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "RéfBidon", "Type Bidon", "Quantité"
            }
        ));
        jScrollPane1.setViewportView(tbEmpruntBidon);

        btCommandeDelete.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btCommandeDelete.setText("Supprimer");
        btCommandeDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(39, 175, 201), 2));
        btCommandeDelete.setContentAreaFilled(false);
        btCommandeDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btCommandeDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btCommandeDeleteMouseExited(evt);
            }
        });
        btCommandeDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCommandeDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btStockBidonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btCommandeDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btUserReset, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCommandeDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btStockBidonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btUserReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btStockBidonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStockBidonSaveActionPerformed
        try {
            if (listEmprunt.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Aucun emprunt n'a été fait ! ", "RidayaSoft : Emprunt bidon", JOptionPane.ERROR_MESSAGE);

            } else if (cbClientNom.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(null, "Verifier le nom du client !", "RidayaSoft : Emprunt bidon", JOptionPane.ERROR_MESSAGE);

            } else {

                // CLIENT
//                Client client = new Client();
//                client.setNomClient(txtNomClient.getText());
//                try {
//                    transaction.begin();
//                    em.persist(client);
//                    transaction.commit();
//                } catch (Exception e) {
//                }
//                Client client = clientMetier.clientParNom(em, cbClientNom.getSelectedItem().toString());
                EntityTransaction transaction = em.getTransaction();

                try {

                    for (Emprunter onlyEmprunter : listEmprunt) {
//                        onlyEmprunter.setIdClient(idClient);
//                        Emprunter emprunterAEnregistrer = new Emprunter();
//                        emprunterAEnregistrer.setBidon(onlyEmprunter.getBidon());
//                        emprunterAEnregistrer.setClient(idClient);
//                        emprunterAEnregistrer.setDateEmprunter(onlyEmprunter.getDateEmprunter());
//                        emprunterAEnregistrer.setQuantiteEmprunter(onlyEmprunter.getQuantiteEmprunter());
                        //onlyEmprunter.setEmprunterPK(emprunterPK);

                        transaction.begin();
                        em.persist(onlyEmprunter);
                        transaction.commit();
                        nombreEmprunt++;
                    }

                    JOptionPane.showMessageDialog(null, "L'emprunt du client " + cbClientNom.getSelectedItem().toString().toUpperCase() + " a été enregistré!", "RidayaSoft : Emprunt Bidon", JOptionPane.INFORMATION_MESSAGE);

                    new Fichier().ecrireFichierLogAccess("Enregistrement de l'emprunt du client " + cbClientNom.getSelectedItem().toString().toUpperCase() + " à " + Date.from(Instant.now()));

                    init();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Deux ou plusieurs produits du meme nom sur le panier : Sommer les produits ayant le même nom !\n \n" + e.getMessage());
                    init();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur, veuillez contacter l'administrateur !");
        }
    }//GEN-LAST:event_btStockBidonSaveActionPerformed
    public void init() {
        cbClientNom.setSelectedIndex(-1);
        cbTypeBidonEmprunt.setSelectedIndex(-1);
        txtQtDispoTypeBidon.setText("");
        txtQtBidonEmprunter.setText("");
        listEmprunt.clear();
        for (int i = model.getRowCount() - 1; i > -1; i--) {
            model.removeRow(i);
        }
    }
    private void btUserResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUserResetActionPerformed
        init();
    }//GEN-LAST:event_btUserResetActionPerformed

    private void btStockBidonSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btStockBidonSaveMouseEntered
        btStockBidonSave.setForeground(Color.red);
    }//GEN-LAST:event_btStockBidonSaveMouseEntered

    private void btStockBidonSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btStockBidonSaveMouseExited
        btStockBidonSave.setForeground(btUserReset.getForeground());
    }//GEN-LAST:event_btStockBidonSaveMouseExited

    private void btUserResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btUserResetMouseEntered
        btUserReset.setForeground(Color.red);
    }//GEN-LAST:event_btUserResetMouseEntered

    private void btUserResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btUserResetMouseExited
        btUserReset.setForeground(btStockBidonSave.getForeground());
    }//GEN-LAST:event_btUserResetMouseExited

    private void txtQtBidonEmprunterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtBidonEmprunterKeyReleased
        if (!metier.isNumeric(evt.getKeyChar())) {
            txtQtBidonEmprunter.setText(txtQtBidonEmprunter.getText().replace(String.valueOf(evt.getKeyChar()), ""));
        }
    }//GEN-LAST:event_txtQtBidonEmprunterKeyReleased

    private void btSavePanierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSavePanierMouseEntered
        btSavePanier.setForeground(Color.red);
    }//GEN-LAST:event_btSavePanierMouseEntered

    private void btSavePanierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSavePanierMouseExited
        btSavePanier.setForeground(Color.black);
    }//GEN-LAST:event_btSavePanierMouseExited
    List<Emprunter> listEmprunt = new ArrayList<>();
    private void btSavePanierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSavePanierActionPerformed
        ajoutPanier();
    }//GEN-LAST:event_btSavePanierActionPerformed
    private void ajoutPanier() {
        try {
            if (Integer.parseInt(txtQtBidonEmprunter.getText()) > Integer.parseInt(txtQtDispoTypeBidon.getText())) {
                JOptionPane.showMessageDialog(null, "La quantité commandée est superieure à la quatité disponible dans le stock !", "RidayaSoft : Emprunt Bidon", JOptionPane.ERROR_MESSAGE);

            } else if (cbClientNom.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(null, "Verifier le nom du client !", "RidayaSoft : Emprunt bidon", JOptionPane.ERROR_MESSAGE);

            } else if (cbTypeBidonEmprunt.getSelectedIndex() == -1 || cbTypeBidonEmprunt.getSelectedItem().toString().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Veuillez choisir le type de Bidon !", "RidayaSoft : Emprunt bidon", JOptionPane.ERROR_MESSAGE);
            } else if (Integer.parseInt(txtQtBidonEmprunter.getText()) < 1) {
                JOptionPane.showMessageDialog(null, "Veuillez introduire la quantité existante !", "RidayaSoft : Emprunt bidon", JOptionPane.ERROR_MESSAGE);
            } else {
                Emprunter emprunter = new Emprunter();
                emprunter.setDateEmprunter(Date.from(Instant.now()));
                emprunter.setQuantiteEmprunter(Integer.parseInt(txtQtBidonEmprunter.getText()));
                emprunter.setIdBidon(idBidon);
                emprunter.setIdClient(idClient);

                listEmprunt.add(emprunter);

                // Table
                model.insertRow(model.getRowCount(), new Object[]{listEmprunt.size(), idBidon.getIdBidon(),
                    idBidon.getTypeBidon(), Integer.parseInt(txtQtBidonEmprunter.getText())});

                cbTypeBidonEmprunt.setSelectedIndex(-1);
                txtQtBidonEmprunter.setText("");
                txtQtDispoTypeBidon.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur : Bidon non ajouté au panier ! ", "Ridaya Soft : Emprunt Bidon", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void btCommandeDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCommandeDeleteMouseEntered
        btCommandeDelete.setForeground(Color.red);
    }//GEN-LAST:event_btCommandeDeleteMouseEntered

    private void btCommandeDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCommandeDeleteMouseExited
        btCommandeDelete.setForeground(Color.black);
    }//GEN-LAST:event_btCommandeDeleteMouseExited

    private void btCommandeDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCommandeDeleteActionPerformed
        listEmprunt.remove(tbEmpruntBidon.getSelectedRow());
        model.removeRow(tbEmpruntBidon.getSelectedRow());

    }//GEN-LAST:event_btCommandeDeleteActionPerformed

    private void cbTypeBidonEmpruntPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbTypeBidonEmpruntPopupMenuWillBecomeInvisible
        try {
            BidonMetier bidonMetier = new BidonMetier();
            idBidon = bidonMetier.bidonParTypeBidon(em, cbTypeBidonEmprunt.getSelectedItem().toString());

            // Etat de stock
            txtQtDispoTypeBidon.setText(new StockMetier().etatDeStockParBidon(em, idBidon.getIdBidon()).get(0).toString());

        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Erreur Emprunt Bidon : " +e.getMessage());
        }
    }//GEN-LAST:event_cbTypeBidonEmpruntPopupMenuWillBecomeInvisible

    private void txtQtDispoTypeBidonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtDispoTypeBidonKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtDispoTypeBidonKeyReleased

    private void cbClientNomPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbClientNomPopupMenuWillBecomeInvisible
        try {
            idClient = clientMetier.clientParNom(em, cbClientNom.getSelectedItem().toString());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cbClientNomPopupMenuWillBecomeInvisible


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCommandeDelete;
    private javax.swing.JButton btSavePanier;
    private javax.swing.JButton btStockBidonSave;
    private javax.swing.JButton btUserReset;
    private javax.swing.JComboBox cbClientNom;
    private javax.swing.JComboBox cbTypeBidonEmprunt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblQtDispoTypeBidon;
    private javax.swing.JTable tbEmpruntBidon;
    private javax.swing.JTextField txtQtBidonEmprunter;
    private javax.swing.JTextField txtQtDispoTypeBidon;
    // End of variables declaration//GEN-END:variables
}
