/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fenetre.EtatStock;

import Entity.Produit;
import Entity.Stock;
import static Fenetre.EtatStock.ModifProduitForm.txtIdProduit;
import Metier.ConnexionBD;
import Metier.Fichier;
import java.time.Instant;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityTransaction;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import ridayasoft.Metier;

/**
 *
 * @author Gauss
 */
public class ModifEntreeStock extends javax.swing.JDialog {

    /**
     * Creates new form ModifEntreeStock
     */
    EntityManager em;
    public ModifEntreeStock(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        try {
            em = new ConnexionBD().getConnexion();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Connexion : " + e.getMessage());
        }
        
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        txtQuantiteProduitModif.setVisible(false);
        txtPrixProduitModif.setVisible(false);
        btModifProduit.setEnabled(false);
    }
    
    
    private void getInfoStock() {
        try {
            Query qr = em.createNamedQuery("Stock.findByIdStock");
            qr.setParameter("idStock", Integer.parseInt(txtIdProduitModif.getText().trim()));
            List<Stock> listStock = qr.getResultList();
            Stock stock = listStock.get(0);
            txtPrixProduitModif.setText(String.valueOf(stock.getPrixAchat()));
            txtQuantiteProduitModif.setText(String.valueOf(stock.getQuantite()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Info : " + e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdProduitModif = new javax.swing.JTextField();
        txtQuantiteProduitModif = new javax.swing.JTextField();
        txtPrixProduitModif = new javax.swing.JTextField();
        btModifProduit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ridaya Soft : Modif Entrée Stock");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modification du produit");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setText("Numéro du produit : ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel4.setText("Quantité : ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel5.setText("Prix d'achat : ");

        txtIdProduitModif.setEditable(false);
        txtIdProduitModif.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtIdProduitModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProduitModifActionPerformed(evt);
            }
        });

        txtQuantiteProduitModif.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtQuantiteProduitModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantiteProduitModifActionPerformed(evt);
            }
        });
        txtQuantiteProduitModif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantiteProduitModifKeyReleased(evt);
            }
        });

        txtPrixProduitModif.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtPrixProduitModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrixProduitModifActionPerformed(evt);
            }
        });
        txtPrixProduitModif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrixProduitModifKeyReleased(evt);
            }
        });

        btModifProduit.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btModifProduit.setText("Modifier");
        btModifProduit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 207, 255)));
        btModifProduit.setContentAreaFilled(false);
        btModifProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModifProduitActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton2.setText("Afficher Info");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 207, 255)));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrixProduitModif, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuantiteProduitModif, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdProduitModif, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btModifProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdProduitModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtQuantiteProduitModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPrixProduitModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btModifProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdProduitModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProduitModifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProduitModifActionPerformed

    private void txtQuantiteProduitModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantiteProduitModifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantiteProduitModifActionPerformed

    private void txtQuantiteProduitModifKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantiteProduitModifKeyReleased
        if (!new Metier().isNumeric(evt.getKeyChar())) {
            txtQuantiteProduitModif.setText(txtQuantiteProduitModif.getText().replace(String.valueOf(evt.getKeyChar()), ""));
        }
    }//GEN-LAST:event_txtQuantiteProduitModifKeyReleased

    private void txtPrixProduitModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrixProduitModifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrixProduitModifActionPerformed

    private void txtPrixProduitModifKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrixProduitModifKeyReleased
 if (!new Metier().isNumeric(evt.getKeyChar())) {
            txtPrixProduitModif.setText(txtPrixProduitModif.getText().replace(String.valueOf(evt.getKeyChar()), ""));
        }       
    }//GEN-LAST:event_txtPrixProduitModifKeyReleased

    private void btModifProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModifProduitActionPerformed
        Stock stock = em.find(Stock.class, Integer.parseInt(txtIdProduitModif.getText()));
        stock.setPrixAchat(Double.parseDouble(txtPrixProduitModif.getText()));
        stock.setQuantite(Integer.parseInt(txtQuantiteProduitModif.getText()));
        
        try {
            EntityTransaction transaction = em.getTransaction();
            transaction.begin();
            em.merge(stock);
            transaction.commit();
            JOptionPane.showMessageDialog(null, "Le stock a été modifié avec succes !", "Ridaya Soft : Modif Stock", JOptionPane.INFORMATION_MESSAGE);
            new Fichier().ecrireFichierLogAccess("Modification du stock "+txtIdProduitModif.getText() + " à partir du " + Date.from(Instant.now()));
            int printFacture = JOptionPane.showConfirmDialog(null, "Voulez vous fermer ?", "RidayaSoft : Modification stock", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (printFacture == JOptionPane.YES_OPTION) {
                this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Pas de modification car " + e.getMessage());
        }
    }//GEN-LAST:event_btModifProduitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jLabel4.setVisible(true);
        jLabel5.setVisible(true);
        txtQuantiteProduitModif.setVisible(true);
        txtPrixProduitModif.setVisible(true);
        btModifProduit.setEnabled(true);
        getInfoStock();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifEntreeStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifEntreeStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifEntreeStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifEntreeStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModifEntreeStock dialog = new ModifEntreeStock(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btModifProduit;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField txtIdProduitModif;
    private javax.swing.JTextField txtPrixProduitModif;
    private javax.swing.JTextField txtQuantiteProduitModif;
    // End of variables declaration//GEN-END:variables
}
