/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fenetre.EtatStock;

import Entity.Produit;
import Metier.ConnexionBD;
import Metier.Fichier;
import java.time.Instant;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityTransaction;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import ridayasoft.Metier;

/**
 *
 * @author Gauss
 */
public class ModifProduitForm extends javax.swing.JDialog {

    /**
     * Creates new form ModifProduitForm
     */
    EntityManager em;

    public ModifProduitForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            em = new ConnexionBD().getConnexion();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Connexion : " + e.getMessage());
        }

        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        txtNomProduit.setVisible(false);
        txtPrixProduit.setVisible(false);
        txtSeuilProduit.setVisible(false);
        btModifProduit.setEnabled(false);

    }

    private void getInfoProduit() {
        try {
            Query qr = em.createNamedQuery("Produit.findByIdProduit");
            qr.setParameter("idProduit", Integer.parseInt(txtIdProduit.getText().trim()));
            List<Produit> listProduit = qr.getResultList();
            Produit produit = listProduit.get(0);
            txtNomProduit.setText(produit.getNomProduit());
            txtPrixProduit.setText(String.valueOf(produit.getPrixUnitaire()));
            txtSeuilProduit.setText(String.valueOf(produit.getSeuil()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Info : " + e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdProduit = new javax.swing.JTextField();
        txtNomProduit = new javax.swing.JTextField();
        txtPrixProduit = new javax.swing.JTextField();
        txtSeuilProduit = new javax.swing.JTextField();
        btModifProduit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ridaya Soft : Modif produit");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modification du produit");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setText("Numéro du produit : ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel3.setText("Nom du produit : ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel4.setText("Prix de vente : ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel5.setText("Seuil : ");

        txtIdProduit.setEditable(false);
        txtIdProduit.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtIdProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProduitActionPerformed(evt);
            }
        });

        txtNomProduit.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtNomProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomProduitActionPerformed(evt);
            }
        });

        txtPrixProduit.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtPrixProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrixProduitActionPerformed(evt);
            }
        });
        txtPrixProduit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrixProduitKeyReleased(evt);
            }
        });

        txtSeuilProduit.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtSeuilProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeuilProduitActionPerformed(evt);
            }
        });
        txtSeuilProduit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSeuilProduitKeyReleased(evt);
            }
        });

        btModifProduit.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btModifProduit.setText("Modifier");
        btModifProduit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 207, 255)));
        btModifProduit.setContentAreaFilled(false);
        btModifProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModifProduitActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton2.setText("Afficher Info");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 207, 255)));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSeuilProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrixProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btModifProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdProduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNomProduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrixProduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSeuilProduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btModifProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProduitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProduitActionPerformed

    private void txtNomProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomProduitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomProduitActionPerformed

    private void txtPrixProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrixProduitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrixProduitActionPerformed

    private void txtSeuilProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeuilProduitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeuilProduitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jLabel5.setVisible(true);
        txtNomProduit.setVisible(true);
        txtPrixProduit.setVisible(true);
        txtSeuilProduit.setVisible(true);
        btModifProduit.setEnabled(true);
        getInfoProduit();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btModifProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModifProduitActionPerformed
        Produit produit = em.find(Produit.class, Integer.parseInt(txtIdProduit.getText()));
        produit.setNomProduit(txtNomProduit.getText());
        produit.setPrixUnitaire(Double.parseDouble(txtPrixProduit.getText()));
        produit.setSeuil(Integer.parseInt(txtSeuilProduit.getText()));

        try {
            EntityTransaction transaction = em.getTransaction();
            transaction.begin();
            em.merge(produit);
            transaction.commit();
            JOptionPane.showMessageDialog(null, "Produit " + txtNomProduit.getText() + " a été modifié avec succes !", "Ridaya Soft : Modif Produit", JOptionPane.INFORMATION_MESSAGE);
             new Fichier().ecrireFichierLogAccess("Modification du produit "+txtNomProduit.getText()+" le prix est maintenant à "+ txtPrixProduit.getText() + " à partir du " + Date.from(Instant.now()));
            int printFacture = JOptionPane.showConfirmDialog(null, "Voulez vous fermer ?", "RidayaSoft : Suppression article", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (printFacture == JOptionPane.YES_OPTION) {
                this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Pas de modification car " + e.getMessage());
        }

    }//GEN-LAST:event_btModifProduitActionPerformed

    private void txtPrixProduitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrixProduitKeyReleased
        if (!new Metier().isNumeric(evt.getKeyChar())) {
            txtPrixProduit.setText(txtPrixProduit.getText().replace(String.valueOf(evt.getKeyChar()), ""));
        }
    }//GEN-LAST:event_txtPrixProduitKeyReleased

    private void txtSeuilProduitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeuilProduitKeyReleased
        if (!new Metier().isNumeric(evt.getKeyChar())) {
            txtSeuilProduit.setText(txtSeuilProduit.getText().replace(String.valueOf(evt.getKeyChar()), ""));
        }
    }//GEN-LAST:event_txtSeuilProduitKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifProduitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifProduitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifProduitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifProduitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModifProduitForm dialog = new ModifProduitForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btModifProduit;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField txtIdProduit;
    private javax.swing.JTextField txtNomProduit;
    private javax.swing.JTextField txtPrixProduit;
    private javax.swing.JTextField txtSeuilProduit;
    // End of variables declaration//GEN-END:variables
}
