/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fenetre.EtatStock;

import Metier.IReport;
import Metier.StockMetier;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ridayasoft.Metier;

/**
 *
 * @author Gauss
 */
public class StockEntree extends javax.swing.JPanel {

    /**
     * Creates new form StockEntree
     */
    EntityManagerFactory emf;
    EntityManager em;
    DefaultTableModel model;
    StockMetier stockMetier = new StockMetier();
    Metier metier = new Metier();
    String dateJour = null;

    public StockEntree() {
        initComponents();
        model = (DefaultTableModel) tbEntreeStock.getModel();
        try {
            emf = Persistence.createEntityManagerFactory("RidayaSoftPU");
            em = emf.createEntityManager();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        listeStock();
    }

    public void listeStock() {
        try {
            List listStock = stockMetier.entreeStock(em);

            for (Object produit : listStock) {
                Object[] produitTab = (Object[]) produit;
                model.insertRow(model.getRowCount(), new Object[]{produitTab[0], produitTab[1], produitTab[2], produitTab[3], produitTab[4]});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void listeStockByDate(String date) {
        try {
            List listStock = stockMetier.entreeStockbyDate(em, date);

            for (Object produit : listStock) {
                Object[] produitTab = (Object[]) produit;
                model.insertRow(model.getRowCount(), new Object[]{produitTab[0], produitTab[1], produitTab[2], produitTab[3], produitTab[4]});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dtJourEntree = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEntreeStock = new javax.swing.JTable();
        btPrintEntree = new javax.swing.JButton();
        btSearchStock = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Entrée des produits");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel2.setText("Jour : ");

        dtJourEntree.setDateFormatString("dd MM yyyy");
        dtJourEntree.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setAutoscrolls(true);

        tbEntreeStock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(39, 175, 201)));
        tbEntreeStock.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tbEntreeStock.setForeground(new java.awt.Color(60, 60, 60));
        tbEntreeStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num Produit", "Nom produit", "Quantité", "Prix d'achat", "Date de stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbEntreeStock.setGridColor(new java.awt.Color(39, 175, 201));
        tbEntreeStock.setInheritsPopupMenu(true);
        tbEntreeStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEntreeStockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbEntreeStock);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btPrintEntree.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btPrintEntree.setForeground(new java.awt.Color(0, 207, 255));
        btPrintEntree.setText("Imprimer");
        btPrintEntree.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 207, 255), 2));
        btPrintEntree.setContentAreaFilled(false);
        btPrintEntree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btPrintEntreeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btPrintEntreeMouseExited(evt);
            }
        });
        btPrintEntree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrintEntreeActionPerformed(evt);
            }
        });

        btSearchStock.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btSearchStock.setForeground(new java.awt.Color(0, 207, 255));
        btSearchStock.setText("Rechercher");
        btSearchStock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 207, 255), 2));
        btSearchStock.setContentAreaFilled(false);
        btSearchStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSearchStockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSearchStockMouseExited(evt);
            }
        });
        btSearchStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dtJourEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(btSearchStock, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btPrintEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(dtJourEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPrintEntree, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(btSearchStock, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btPrintEntreeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPrintEntreeMouseEntered
        btPrintEntree.setForeground(Color.red);
    }//GEN-LAST:event_btPrintEntreeMouseEntered

    private void btPrintEntreeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPrintEntreeMouseExited
        btPrintEntree.setForeground(Color.cyan);
    }//GEN-LAST:event_btPrintEntreeMouseExited

    private void btPrintEntreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrintEntreeActionPerformed
        String chemin = getClass().getResource("/Report/entreeStockReport.jrxml").toString().replace("file:/", "");
        try {
            if (dateJour.isEmpty()) {
                try {
                    new IReport().reportStatique(chemin);
                } catch (Exception e) {
                }

            } else {
                int printFacture = JOptionPane.showConfirmDialog(null, "Pour toutes entrées, appuyer sur OUI\n"
                        + "Pour celles de la dernière recherche appuyer sur NON", "RidayaSoft : Etat stock", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (printFacture == JOptionPane.YES_OPTION) {
                    new IReport().reportStatique(chemin);
                } else {
                    String sql = "SELECT produit.idProduit, produit.nomProduit, SUM( stock.quantite ) AS quantite, stock.prixAchat, stock.dateStock"
                               + "FROM produit "
                               + "INNER JOIN stock ON produit.idProduit = stock.idProduit "
                               + "WHERE stock.dateStock LIKE '" + dateJour + "%' "
                               + "GROUP BY produit.idProduit, produit.nomProduit, stock.prixAchat, stock.dateStock "
                               + "ORDER BY stock.dateStock ";
                    new IReport().reportDynamique(chemin, sql);
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btPrintEntreeActionPerformed

    private void btSearchStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchStockActionPerformed
        try {
            if (dtJourEntree.getDate().toString().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Pas de date choisi ! ", "RidayaSoft : Entrée stock", JOptionPane.ERROR_MESSAGE);
            } else {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String date = sdf.format(dtJourEntree.getDate());
                dateJour = date;
                if (model.getRowCount() > 0) {
                    for (int i = model.getRowCount() - 1; i > -1; i--) {
                        model.removeRow(i);
                    }
                }
                listeStockByDate(dateJour);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Date inconnu : Verifie la date de recherche", "RidayaSoft : Entrée stock", JOptionPane.ERROR_MESSAGE);
            listeStock();
        }
    }//GEN-LAST:event_btSearchStockActionPerformed

    private void btSearchStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSearchStockMouseExited
        btSearchStock.setForeground(Color.cyan);
    }//GEN-LAST:event_btSearchStockMouseExited

    private void btSearchStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSearchStockMouseEntered
        btSearchStock.setForeground(Color.red);
    }//GEN-LAST:event_btSearchStockMouseEntered

    private void tbEntreeStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEntreeStockMouseClicked
       if (evt.getClickCount() == 2) {
            ModifEntreeStock d = new ModifEntreeStock(null, true);
            d.txtIdProduitModif.setText(String.valueOf(model.getValueAt(tbEntreeStock.getSelectedRow(), 0)));
            d.setVisible(true);
        }
    }//GEN-LAST:event_tbEntreeStockMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPrintEntree;
    private javax.swing.JButton btSearchStock;
    private com.toedter.calendar.JDateChooser dtJourEntree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbEntreeStock;
    // End of variables declaration//GEN-END:variables
}
