/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fenetre.EtatStock;

import Metier.IReport;
import Metier.StockMetier;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ridayasoft.Metier;

/**
 *
 * @author Gauss
 */
public class StockSortie extends javax.swing.JPanel {

    /**
     * Creates new form StockSortie
     */
    EntityManagerFactory emf;
    EntityManager em;
    DefaultTableModel model;
    StockMetier stockMetier = new StockMetier();
    Metier metier = new Metier();
    String dateJour = null;
    String dateStart;
    String dateEnd;

    public StockSortie() {
        initComponents();

        model = (DefaultTableModel) tbSortieStock.getModel();
        try {
            emf = Persistence.createEntityManagerFactory("RidayaSoftPU");
            em = emf.createEntityManager();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        listeStock();
    }

    public void listeStock() {
        try {
            List listStock = stockMetier.sortieStock(em);

            for (Object produit : listStock) {
                Object[] produitTab = (Object[]) produit;
                model.insertRow(model.getRowCount(), new Object[]{produitTab[0], produitTab[1], produitTab[2], produitTab[3], produitTab[4]});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
     public void listeStockMafia(String date) {
        try {
            List listStock = stockMetier.stockMafia(em, date);

            for (Object produit : listStock) {
                Object[] produitTab = (Object[]) produit;
                model.insertRow(model.getRowCount(), new Object[]{produitTab[0], produitTab[1], produitTab[2], produitTab[3], produitTab[4]});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void listeStockByDate(String dateStart, String dateEnd) {
        try {
            List listStock = stockMetier.sortieStockByDate(em, dateStart, dateEnd);

            for (Object produit : listStock) {
                Object[] produitTab = (Object[]) produit;
                model.insertRow(model.getRowCount(), new Object[]{produitTab[0], produitTab[1], produitTab[2], produitTab[3], produitTab[4]});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSortieStock = new javax.swing.JTable();
        btPrintEntree = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        dtJourEntree = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        dtJourSortie = new com.toedter.calendar.JDateChooser();
        btPrintEntree2 = new javax.swing.JButton();
        btPrintSortieSearch = new javax.swing.JButton();
        btPrintEntree1 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sortie des produits");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setAutoscrolls(true);

        tbSortieStock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(39, 175, 201)));
        tbSortieStock.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tbSortieStock.setForeground(new java.awt.Color(60, 60, 60));
        tbSortieStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num Produit", "Nom produit", "Quantité", "Prix vente", "Date facturation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSortieStock.setGridColor(new java.awt.Color(39, 175, 201));
        tbSortieStock.setInheritsPopupMenu(true);
        jScrollPane1.setViewportView(tbSortieStock);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btPrintEntree.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btPrintEntree.setForeground(new java.awt.Color(0, 207, 255));
        btPrintEntree.setText("Imprimer toutes les sorties ");
        btPrintEntree.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 207, 255), 2));
        btPrintEntree.setContentAreaFilled(false);
        btPrintEntree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btPrintEntreeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btPrintEntreeMouseExited(evt);
            }
        });
        btPrintEntree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrintEntreeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel2.setText("Jour start : ");

        dtJourEntree.setDateFormatString("dd MM yyyy");
        dtJourEntree.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel3.setText("Jour end : ");

        dtJourSortie.setDateFormatString("dd MM yyyy");
        dtJourSortie.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        btPrintEntree2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btPrintEntree2.setForeground(new java.awt.Color(0, 207, 255));
        btPrintEntree2.setText("Rechercher");
        btPrintEntree2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 207, 255)));
        btPrintEntree2.setContentAreaFilled(false);
        btPrintEntree2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btPrintEntree2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btPrintEntree2MouseExited(evt);
            }
        });
        btPrintEntree2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrintEntree2ActionPerformed(evt);
            }
        });

        btPrintSortieSearch.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btPrintSortieSearch.setForeground(new java.awt.Color(0, 207, 255));
        btPrintSortieSearch.setText("Imprimer la derniere recherche");
        btPrintSortieSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 207, 255), 2));
        btPrintSortieSearch.setContentAreaFilled(false);
        btPrintSortieSearch.setEnabled(false);
        btPrintSortieSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btPrintSortieSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btPrintSortieSearchMouseExited(evt);
            }
        });
        btPrintSortieSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrintSortieSearchActionPerformed(evt);
            }
        });

        btPrintEntree1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btPrintEntree1.setForeground(new java.awt.Color(0, 207, 255));
        btPrintEntree1.setText("Vente");
        btPrintEntree1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 207, 255), 2));
        btPrintEntree1.setContentAreaFilled(false);
        btPrintEntree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btPrintEntree1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btPrintEntree1MouseExited(evt);
            }
        });
        btPrintEntree1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrintEntree1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(btPrintSortieSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(btPrintEntree1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btPrintEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dtJourEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dtJourSortie, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btPrintEntree2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 63, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(dtJourEntree, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtJourSortie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPrintEntree2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPrintEntree, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(btPrintSortieSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(btPrintEntree1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
Color couleur;
    private void btPrintEntreeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPrintEntreeMouseEntered
        couleur = btPrintEntree.getForeground();
        btPrintEntree.setForeground(Color.red);
    }//GEN-LAST:event_btPrintEntreeMouseEntered

    private void btPrintEntreeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPrintEntreeMouseExited
        btPrintEntree.setForeground(couleur);
    }//GEN-LAST:event_btPrintEntreeMouseExited

    private void btPrintEntreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrintEntreeActionPerformed
        try {
           
            new IReport().reportStatique(getClass().getResource("/Report/SortieStockReport.jrxml").toString().replace("file:/", ""));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btPrintEntreeActionPerformed

    private void btPrintEntree2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPrintEntree2MouseEntered
       couleur = btPrintEntree2.getForeground();
        btPrintEntree2.setForeground(Color.RED);
    }//GEN-LAST:event_btPrintEntree2MouseEntered

    private void btPrintEntree2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPrintEntree2MouseExited
        btPrintEntree2.setForeground(couleur);
    }//GEN-LAST:event_btPrintEntree2MouseExited

    private void btPrintEntree2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrintEntree2ActionPerformed
        try {
            if (dtJourEntree.getDate().toString().isEmpty() || dtJourSortie.getDate().toString().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Pas de date choisi ! ", "RidayaSoft : Sortie stock", JOptionPane.ERROR_MESSAGE);
            } else if (dtJourEntree.getDate().after(dtJourSortie.getDate())) {
                JOptionPane.showMessageDialog(null, "La date start vient après la date end ", "RidayaSoft : Sortie stock", JOptionPane.ERROR_MESSAGE);
            } else {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                dateStart = sdf.format(dtJourEntree.getDate());
//                dateJour = date;

                dateEnd = sdf.format(dtJourSortie.getDate());

                if (model.getRowCount() > 0) {
                    for (int i = model.getRowCount() - 1; i > -1; i--) {
                        model.removeRow(i);
                    }
                }
                listeStockByDate(dateStart, dateEnd);
                btPrintSortieSearch.setEnabled(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Date inconnu : Verifie la date de recherche", "RidayaSoft : Entrée stock", JOptionPane.ERROR_MESSAGE);
            // listeStock();
        }
    }//GEN-LAST:event_btPrintEntree2ActionPerformed

    private void btPrintSortieSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPrintSortieSearchMouseEntered
      couleur = btPrintSortieSearch.getForeground();
        btPrintSortieSearch.setForeground(Color.RED);
    }//GEN-LAST:event_btPrintSortieSearchMouseEntered

    private void btPrintSortieSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPrintSortieSearchMouseExited
       btPrintSortieSearch.setForeground(couleur);
    }//GEN-LAST:event_btPrintSortieSearchMouseExited

    private void btPrintSortieSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrintSortieSearchActionPerformed
        try {
            String sql = "SELECT produit.idProduit, produit.nomProduit, SUM( commander.quantiteCommande ) AS quantite, commander.prixVenteCommande, facture.dateFacture\n"
                + "FROM produit\n"
                + "INNER JOIN commander ON produit.idProduit = commander.idProduit\n"
                + "INNER JOIN client ON client.idClient = commander.IdClient\n"
                + "INNER JOIN facture ON facture.idClient = client.idClient\n"
                + "WHERE facture.dateFacture BETWEEN '"+dateStart+" 00:00:00' AND '"+dateEnd+" 23:59:00'\n"
                + "GROUP BY produit.idProduit, produit.nomProduit, commander.prixVenteCommande, facture.dateFacture\n"
                + "ORDER BY facture.dateFacture";
        
        new IReport().reportDynamique("C:\\Users\\Gauss\\Documents\\NetBeansProjects\\RidayaSoft\\Rapport\\SortieStockReport.jrxml", sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_btPrintSortieSearchActionPerformed

    private void btPrintEntree1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPrintEntree1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btPrintEntree1MouseEntered

    private void btPrintEntree1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPrintEntree1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btPrintEntree1MouseExited

    private void btPrintEntree1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrintEntree1ActionPerformed
       new Metier().supTab(model);
       
        listeStockMafia(new Metier().dateCourante());
    }//GEN-LAST:event_btPrintEntree1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPrintEntree;
    private javax.swing.JButton btPrintEntree1;
    private javax.swing.JButton btPrintEntree2;
    private javax.swing.JButton btPrintSortieSearch;
    private com.toedter.calendar.JDateChooser dtJourEntree;
    private com.toedter.calendar.JDateChooser dtJourSortie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbSortieStock;
    // End of variables declaration//GEN-END:variables
}
